export interface VideoItem {
  id: string;
  title: string;
  channelId?: string;
  channelTitle?: string;
  channelThumbnail?: string;
  thumbnail?: string;
  durationText?: string;
  viewCountText?: string;
  publishedText?: string;
  description?: string;
  isShort?: boolean;
  isLive?: boolean;
  isUpcoming?: boolean;
  badges?: string[];
  type?: 'video' | 'channel' | 'playlist' | 'movie';
}

export interface ManifestStream {
  itag: number;
  mimeType?: string;
  container?: string;
  codecs?: string;
  quality?: string;
  qualityLabel?: string;
  bitrate?: number;
  fps?: number;
  width?: number;
  height?: number;
  audioChannels?: number;
  hasVideo?: boolean;
  hasAudio?: boolean;
  url: string;
  playbackMode?: 'direct' | 'dash' | 'hls' | 'auto';
  targetHeight?: number;
  audioItag?: number;
  audioUrl?: string;
  audioCodec?: string;
  contentLength?: number | null;
  approxDurationMs?: number | null;
  initRange?: { start: number; end: number } | null;
  indexRange?: { start: number; end: number } | null;
  audioSampleRate?: number | null;
}

export interface ManifestPayload {
  metadata?: {
    id: string;
    title?: string;
    author?: string;
    lengthSeconds?: number;
    thumbnails?: string[];
  };
  defaultStream?: ManifestStream;
  muxed?: ManifestStream[];
  videoOnly?: ManifestStream[];
  audioOnly?: ManifestStream[];
  dashManifestUrl?: string | null;
  hlsManifestUrl?: string | null;
  sabrStreamingUrl?: string | null;
  sabrUstreamerConfig?: string | null;
  nativeHlsUrl?: string | null;
}

export interface CaptionTrack {
  languageCode: string;
  name?: string;
  isAutoGenerated?: boolean;
}

export interface TranscriptSegment {
  text: string;
  startMs: number;
  durationMs: number;
}

export interface ChannelSummary {
  id: string;
  title: string;
  description?: string;
  thumbnail?: string;
  banner?: string;
  subscriberCount?: string;
  handle?: string;
  videoCount?: string;
  viewCount?: string;
  joinedDate?: string;
  country?: string;
  links?: Array<{ title: string; url: string }>;
}

export interface Subscription {
  channelId: string;
  title: string;
  handle?: string;
  thumbnail?: string;
  banner?: string;
  subscribedAt?: string;
}
