import { getYouTube, stableFetch, isYouTubeClientCoolingDown } from '../lib/youtube.js';
import { CaptionsPayload, TranscriptPayload, TranscriptSegment } from '../lib/types.js';
import { stringifyText, enforceCacheLimit } from '../lib/youtube.utils.js';

const captionsCache = new Map<string, { data: CaptionsPayload, timestamp: number }>();
const transcriptCache = new Map<string, { data: TranscriptPayload, timestamp: number }>();

export class CaptionService {
  private static CACHE_TTL_CAPTIONS = 24 * 60 * 60 * 1000;
  private static CACHE_TTL_TRANSCRIPT = 24 * 60 * 60 * 1000;

  static async getCaptions(videoId: string): Promise<CaptionsPayload> {
    const cached = captionsCache.get(videoId);
    if (cached && Date.now() - cached.timestamp < this.CACHE_TTL_CAPTIONS) {
      return cached.data;
    }

    let captions: any;
    try {
      const yt = await getYouTube('WEB');
      const info = await yt.getInfo(videoId);
      captions = info.captions;
    } catch (error) {
      const payload: CaptionsPayload = { videoId, tracks: [], translationLanguages: [] };
      captionsCache.set(videoId, { data: payload, timestamp: Date.now() });
      console.warn('[CaptionService] captions unavailable:', error);
      return payload;
    }

    const payload: CaptionsPayload = {
      videoId,
      tracks: (Array.isArray(captions?.caption_tracks) ? captions.caption_tracks : []).map((track: any) => ({
        languageCode: track.language_code,
        label: stringifyText(track.name),
        vssId: track.vss_id,
        baseUrl: `${track.base_url || ''}`,
        kind: track.kind || null,
        isTranslatable: Boolean(track.is_translatable),
        isAutoGenerated: track.kind === 'asr' || `${track.vss_id || ''}`.startsWith('a.')
      })),
      translationLanguages: (Array.isArray(captions?.translation_languages) ? captions.translation_languages : []).map((language: any) => ({
        languageCode: language.language_code,
        label: stringifyText(language.language_name)
      }))
    };

    enforceCacheLimit(captionsCache, 500);
    captionsCache.set(videoId, { data: payload, timestamp: Date.now() });
    return payload;
  }

  static async getTranscript(videoId: string, languageCode?: string, translationLanguageCode?: string): Promise<TranscriptPayload> {
    const cacheKey = `${videoId}:${languageCode || ''}:${translationLanguageCode || ''}`;
    const cached = transcriptCache.get(cacheKey);
    if (cached && Date.now() - cached.timestamp < this.CACHE_TTL_TRANSCRIPT) {
      return cached.data;
    }

    const yt = await getYouTube('WEB');
    const info = await yt.getInfo(videoId);
    const captions: any = info.captions;
    const track = this.pickCaptionTrack(captions, languageCode);

    if (!track) {
      throw new Error('No captions available');
    }

    const transcriptUrl = this.buildCaptionUrl(track, 'json3', translationLanguageCode);
    const response = await stableFetch(transcriptUrl, {
      headers: this.buildTimedTextHeaders(videoId)
    }, 'WEB');
    const rawText = await response.text();
    let segments: TranscriptSegment[] = [];

    if (response.ok && !this.isLikelyHtml(rawText, response.headers.get('content-type'))) {
      try {
        const parsed = JSON.parse(rawText);
        segments = this.normalizeTranscriptEvents(parsed?.events);
      } catch {
        segments = [];
      }
    }

    if (segments.length === 0) {
      const xmlUrl = new URL(track.base_url);
      if (translationLanguageCode) {
        xmlUrl.searchParams.set('tlang', translationLanguageCode);
      }
      const xmlResponse = await stableFetch(xmlUrl.toString(), {
        headers: this.buildTimedTextHeaders(videoId)
      }, 'WEB');
      const xmlText = await xmlResponse.text();
      if (xmlResponse.ok && !this.isLikelyHtml(xmlText, xmlResponse.headers.get('content-type'))) {
        segments = this.normalizeTranscriptXml(xmlText);
      }
    }

    const payload: TranscriptPayload = {
      videoId,
      languageCode: track.language_code,
      translationLanguageCode: translationLanguageCode || null,
      isAutoGenerated: track.kind === 'asr' || `${track.vss_id || ''}`.startsWith('a.'),
      label: stringifyText(track.name),
      segments
    };

    enforceCacheLimit(transcriptCache, 200);
    transcriptCache.set(cacheKey, { data: payload, timestamp: Date.now() });
    return payload;
  }

  static async downloadCaptionTrack(videoId: string, languageCode?: string, translationLanguageCode?: string, format: 'vtt' | 'ttml' | 'json3' = 'vtt') {
    const captions = await this.getCaptions(videoId);
    const track = languageCode
      ? captions.tracks.find((item) => item.languageCode === languageCode)
      || captions.tracks.find((item) => item.languageCode.startsWith(languageCode))
      : captions.tracks[0];

    if (!track) {
      return this.emptyCaptionTrack(format, languageCode);
    }

    let response: Response;
    let body: string;
    let contentType: string;
    try {
      const cachedUrl = this.buildCaptionUrlFromBase(track.baseUrl, format, translationLanguageCode);
      response = await stableFetch(cachedUrl, { headers: this.buildTimedTextHeaders(videoId) }, 'WEB');
      body = await response.text();
      contentType = response.headers.get('content-type') || (format === 'json3' ? 'application/json; charset=utf-8' : 'text/plain; charset=utf-8');
    } catch (error) {
      console.warn('[CaptionService] caption download skipped:', error);
      return this.emptyCaptionTrack(format, track.languageCode || languageCode);
    }

    if (!response.ok || this.isLikelyHtml(body, contentType)) {
      try {
        if (isYouTubeClientCoolingDown('WEB')) {
          throw new Error('Client WEB is cooling down');
        }
        const yt = await getYouTube('WEB');
        const info = await yt.getInfo(videoId);
        const freshTrack = this.pickCaptionTrack(info.captions, languageCode);
        if (!freshTrack) {
          return this.emptyCaptionTrack(format, track.languageCode);
        }
        const freshUrl = this.buildCaptionUrl(freshTrack, format, translationLanguageCode);
        response = await stableFetch(freshUrl, { headers: this.buildTimedTextHeaders(videoId) }, 'WEB');
        body = await response.text();
        contentType = response.headers.get('content-type') || contentType;
      } catch (error) {
        console.warn('[CaptionService] caption refresh skipped:', error);
        return this.emptyCaptionTrack(format, track.languageCode);
      }
    }

    return {
      body,
      contentType,
      languageCode: track.languageCode,
      label: track.label
    };
  }

  // --- Caption Helpers ---

  private static pickCaptionTrack(captions: any, languageCode?: string) {
    if (!captions || !Array.isArray(captions.caption_tracks)) return null;
    const tracks = captions.caption_tracks;
    if (languageCode) {
      return tracks.find((t: any) => t.language_code === languageCode)
        || tracks.find((t: any) => t.language_code.startsWith(languageCode))
        || tracks[0];
    }
    return tracks[0];
  }

  private static buildCaptionUrl(track: any, format: string, tlang?: string): string {
    const url = new URL(track.base_url);
    url.searchParams.set('fmt', format);
    if (tlang) url.searchParams.set('tlang', tlang);
    return url.toString();
  }

  private static buildCaptionUrlFromBase(baseUrl: string, format: string, tlang?: string): string {
    const url = new URL(baseUrl);
    url.searchParams.set('fmt', format);
    if (tlang) url.searchParams.set('tlang', tlang);
    return url.toString();
  }

  private static buildTimedTextHeaders(videoId: string): Record<string, string> {
    return {
      'Origin': 'https://www.youtube.com',
      'Referer': `https://www.youtube.com/watch?v=${videoId}`,
      'Accept': '*/*'
    };
  }

  private static normalizeTranscriptEvents(events: any[]): TranscriptSegment[] {
    if (!Array.isArray(events)) return [];
    return events
      .filter((event: any) => event?.segs && Array.isArray(event.segs))
      .map((event: any) => ({
        startMs: event.tStartMs || 0,
        durationMs: event.dDurationMs || 0,
        text: event.segs.map((s: any) => s.utf8 || '').join('').trim()
      }))
      .filter((seg: TranscriptSegment) => seg.text.length > 0);
  }

  private static normalizeTranscriptXml(xml: string): TranscriptSegment[] {
    const segments: TranscriptSegment[] = [];
    const textMatches = xml.matchAll(/<text start="(.*?)" dur="(.*?)".*?>(.*?)<\/text>/gs);
    for (const match of textMatches) {
      segments.push({
        startMs: Math.floor(parseFloat(match[1]) * 1000),
        durationMs: Math.floor(parseFloat(match[2]) * 1000),
        text: stringifyText(match[3]).trim()
      });
    }
    return segments.filter((seg: TranscriptSegment) => seg.text.length > 0);
  }

  private static isLikelyHtml(text: string, contentType?: string | null): boolean {
    if (contentType?.includes('text/html')) return true;
    return text.trim().startsWith('<!doctype html') || text.trim().startsWith('<html');
  }

  private static emptyCaptionTrack(format: string, languageCode?: string) {
    return {
      body: format === 'json3' ? '{}' : '',
      contentType: format === 'json3' ? 'application/json' : 'text/vtt',
      languageCode: languageCode || 'und',
      label: 'Unavailable'
    };
  }
}
