/**
 * アプリケーション全体で使用する共通の型定義
 */

export type YouTubeClientType = 'TV' | 'ANDROID_VR' | 'ANDROID' | 'WEB' | 'MWEB' | 'IOS' | 'WEB_REMIX' | 'WEB_SAFARI';

export interface TimedLyricLine {
  time: number;
  text: string;
}

export interface LyricsPayload {
  kind: 'timed' | 'plain' | 'none';
  source: 'lrclib' | 'youtube' | 'generated' | 'none';
  isEstimated: boolean;
  lines: TimedLyricLine[];
  plainText: string | null;
}

export interface SearchTrack {
  id: string;
  title: string;
  artist: string;
  artistId: string | null;
  thumbnail: string;
  duration: string;
}

export interface SearchCollection {
  id: string;
  title: string;
  type: 'album' | 'single' | 'playlist';
  artist: string | null;
  artistId: string | null;
  thumbnail: string;
  subtitle: string;
  year: string;
  itemCount: string;
}

export interface RelatedItem {
  id: string;
  title: string;
  type: 'song' | 'album' | 'single' | 'playlist' | 'artist' | 'video' | 'unknown';
  artist: string | null;
  artistId: string | null;
  thumbnail: string;
  subtitle: string;
  duration: string;
  year: string;
  itemCount: string;
}

export interface RelatedSection {
  title: string;
  items: RelatedItem[];
}

export interface PlaylistPayload {
  id: string;
  title: string;
  type: 'playlist';
  subtitle: string;
  description: string;
  thumbnail: string;
  tracks: SearchTrack[];
  related: RelatedItem[];
}

export interface AlbumPayload {
  id: string;
  title: string;
  type: 'album' | 'single';
  artist: string;
  artistId: string | null;
  subtitle: string;
  description: string;
  thumbnail: string;
  year: string;
  tracks: SearchTrack[];
  related: RelatedItem[];
}

export interface RelatedPayload {
  id: string;
  sections: RelatedSection[];
}

export interface VideoSummary {
  id: string;
  title: string;
  author: string;
  authorId: string | null;
  authorUrl: string | null;
  thumbnail: string;
  duration: string;
  durationText?: string;
  viewCount: string;
  viewCountText?: string;
  published: string;
  publishedText?: string;
  description: string;
  isLive: boolean;
  isUpcoming: boolean;
  isShort: boolean;
  type: string;
  badges?: string[];
  channelId?: string;
  channelTitle?: string;
  channelThumbnail?: string;
}

export interface HomeShelf {
  title: string;
  items: VideoSummary[];
}

export interface HomeFeedPayload {
  header?: {
    title: string;
  };
  shelves: HomeShelf[];
  continuation?: string;
}

export interface SearchVideosPayload {
  items: VideoSummary[];
  continuation?: string;
}

export interface VideoDetailsPayload {
  id: string;
  title: string;
  description: string;
  thumbnail: string;
  duration: string;
  durationSeconds: number;
  viewCount: number;
  likeCount: number | null;
  published: string;
  category: string;
  tags: string[];
  author: string;
  authorId: string | null;
  authorUrl: string | null;
  authorThumbnail?: string;
  authorSubscriberCount?: string;
  isLive: boolean;
  isUpcoming: boolean;
  recommendations: VideoSummary[];
}

export interface CommentSummary {
  id: string;
  content: string;
  published: string;
  author: string;
  authorId: string | null;
  authorUrl: string | null;
  authorThumbnail: string;
  likeCount: string;
  replyCount: string;
  isPinned: boolean;
  isHearted: boolean;
  isVerified: boolean;
  isOwner?: boolean;
}

export interface CommentsPayload {
  videoId: string;
  count: string;
  sort: 'TOP_COMMENTS' | 'NEWEST_FIRST';
  comments: CommentSummary[];
  continuation: string | null;
}

export interface ChannelDetailsPayload {
  id: string;
  name: string;
  handle: string;
  description: string;
  thumbnail: string;
  banner: string;
  subscriberCount: string;
  videoCount: string;
  viewCount?: string;
  joinedDate?: string;
  country?: string;
  links?: { title: string; url: string }[];
  isVerified: boolean;
  isVerifiedArtist: boolean;
  videos: VideoSummary[];
  shorts: VideoSummary[];
  live: VideoSummary[];
  clips: VideoSummary[];
  sections: ChannelSection[];
}

export interface ChannelSection {
  title: string;
  items: VideoSummary[];
  type: string;
}

export interface PlaylistVideosPayload {
  id: string;
  title: string;
  description: string;
  thumbnail: string;
  author: string;
  authorId: string | null;
  totalItems: string;
  items: VideoSummary[];
  offset: number;
  limit: number;
  hasMore: boolean;
  continuation?: string;
}

export interface CaptionTrackSummary {
  languageCode: string;
  label: string;
  vssId: string;
  baseUrl: string;
  kind: string | null;
  isTranslatable: boolean;
  isAutoGenerated: boolean;
}

export interface TranslationLanguageSummary {
  languageCode: string;
  label: string;
}

export interface CaptionsPayload {
  videoId: string;
  tracks: CaptionTrackSummary[];
  translationLanguages: TranslationLanguageSummary[];
}

export interface TranscriptSegment {
  startMs: number;
  durationMs: number;
  text: string;
}

export interface TranscriptPayload {
  videoId: string;
  languageCode: string;
  translationLanguageCode: string | null;
  isAutoGenerated: boolean;
  label: string;
  segments: TranscriptSegment[];
}

export interface FeedEntry {
  id: string; // videoId
  videoId: string;
  channelId: string;
  channelTitle: string;
  author: string; // alias
  authorId: string; // alias
  title: string;
  published: string;
  updated: string;
  description: string;
  thumbnail: string;
  link: string;
}

export interface ChannelFeedPayload {
  channelId: string;
  title: string;
  rssUrl: string;
  entries: FeedEntry[];
}

export interface ManifestStream {
  itag: number;
  mimeType: string;
  container: string;
  codecs: string;
  quality: string;
  qualityLabel: string;
  bitrate: number;
  fps: number | null;
  width: number | null;
  height: number | null;
  audioChannels: number | null;
  hasVideo: boolean;
  hasAudio: boolean;
  url: string;
  originalUrl?: string | null;
  signatureCipher?: string | null;
  cipher?: string | null;
  contentLength: number | null;
  approxDurationMs: number | null;
  initRange: { start: number; end: number } | null;
  indexRange: { start: number; end: number } | null;
  audioSampleRate: number | null;
  duration: number; // calculated convenience
  clientType?: string;
}

export interface ManifestPayload {
  metadata: {
    id: string;
    title: string;
    artist: string;
    artistId: string | null;
    thumbnail: string;
    duration: string;
  };
  defaultStream: ManifestStream | null;
  muxed: ManifestStream[];
  videoOnly: ManifestStream[];
  audioOnly: ManifestStream[];
  dashManifestUrl: string | null;
  hlsManifestUrl: string | null;
  sabrStreamingUrl?: string | null;
  sabrUstreamerConfig?: string | null;
  nativeHlsUrl?: string | null;
}
